name: build data layer

on:
  pull_request:
    paths:
      - .github/workflows/build data layer.yml
      - 'data/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build android app
        run: ./gradlew :data:build